language: node_js
node_js:
  - "7"
  - "6"
  - "5"
cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache
before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install:
  - yarn global add lerna@prerelease
  - yarn global add codecov@latest
script:
  - lerna exec --concurrency=1 -- yarn
  - npm run coverage
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
